### ISSUE TITLE
Configure and kick the tires on Homebrew in linux

### ISSUE THREAD

**Issue by jRobbk** [jRob2k/respawn#6]
See how well homebrew in the linux container works with the bootstrap scripts and the like. If it makes sense, add to respawn!!!!

Install using `CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Tip from [this issue](https://github.com/Homebrew/install/issues/369)

Add to path with instructions [from here](https://docs.brew.sh/Homebrew-on-Linux)

**Comment by jRob2k** [comment]
Implemented. May have some bugs, but i'll open new issues as needed
